services:
  agent:
    image: ${AGENT_IMAGE:-project-yahl-agent:latest}
    build:
      context: ..
      dockerfile: runtime/Dockerfile.agent
    env_file:
      - ../.env
    environment:
      AGENT_CONTAINER_NAME: ${AGENT_CONTAINER_NAME:-agent}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    # test llm, in reality do not allow host connection
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../workspace:/root
      - ./agent/Agent.md:/opt/agent/Agent.md:ro
      - ./orchestrator/YAHL:/opt/yahl:ro
      - ./orchestrator/SKILLS:/opt/skills:ro
    command: ["pnpm", "--silent", "--filter", "runtime", "run", "agent", "--", "--daemon"]
    container_name: ${AGENT_CONTAINER_NAME:-agent}
    networks:
      - shared

networks:
  shared:
    external: true
    name: ${SHARED_DOCKER_NETWORK:-yahl_shared}
