import fs from 'fs/promises';
import path from 'path';

import { config, paths } from '../config.js';

export type TCrashContext = {
  args?: Record<string, unknown>;
  caller?: string;
  error: unknown;
  mode?: string;
  promptPreview?: string;
  sessionId?: string;
  skill?: string;
};

const PROMPT_PREVIEW_LIMIT = 2_000;

const pad = (value: number) => String(value).padStart(2, '0');

const crashReportFilename = (at: Date) => {
  const yyyy = at.getUTCFullYear();
  const mm = pad(at.getUTCMonth() + 1);
  const dd = pad(at.getUTCDate());
  const hh = pad(at.getUTCHours());
  const min = pad(at.getUTCMinutes());
  const ss = pad(at.getUTCSeconds());

  return `${yyyy}-${mm}-${dd}-${hh}${min}${ss}.md`;
};

const formatErrorChain = (error: unknown, depth = 0): string => {
  if (error === null || error === undefined) {
    return `${'  '.repeat(depth)}(no error)`;
  }

  if (typeof error !== 'object') {
    return `${'  '.repeat(depth)}${String(error)}`;
  }

  const err = error as Error & {
    cause?: unknown;
    code?: unknown;
    details?: unknown[];
    rawMessage?: unknown;
  };
  const lines = [
    `${'  '.repeat(depth)}- **message**: ${err.message ?? String(error)}`,
  ];

  if (err.name) {
    lines.push(`${'  '.repeat(depth)}- **name**: ${err.name}`);
  }

  if (err.code !== undefined) {
    lines.push(`${'  '.repeat(depth)}- **code**: ${String(err.code)}`);
  }

  if (err.rawMessage !== undefined) {
    lines.push(`${'  '.repeat(depth)}- **rawMessage**: ${String(err.rawMessage)}`);
  }

  if (err.details?.length) {
    lines.push(`${'  '.repeat(depth)}- **details**:`);

    for (const detail of err.details) {
      if (detail && typeof detail === 'object' && 'type' in detail) {
        const typed = detail as { debug?: unknown; type?: unknown };
        lines.push(`${'  '.repeat(depth + 1)}- **type**: ${String(typed.type)}`);

        if (typed.debug !== undefined) {
          lines.push(`${'  '.repeat(depth + 1)}- **debug**: \`${JSON.stringify(typed.debug)}\``);
        }
      } else {
        lines.push(`${'  '.repeat(depth + 1)}- \`${JSON.stringify(detail)}\``);
      }
    }
  }

  if (err.stack) {
    lines.push(`${'  '.repeat(depth)}- **stack**:\n\`\`\`\n${err.stack}\n\`\`\``);
  }

  if (err.cause !== undefined) {
    lines.push(`${'  '.repeat(depth)}- **cause**:`);
    lines.push(formatErrorChain(err.cause, depth + 1));
  }

  return lines.join('\n');
};

export const formatShortError = (error: unknown): string => {
  if (error instanceof Error) {
    return error.message;
  }

  return String(error);
};

const buildCrashReportBody = (ctx: TCrashContext, at: Date) => {
  const promptPreview = (ctx.promptPreview ?? '(none)').slice(0, PROMPT_PREVIEW_LIMIT);

  return [
    '# Mastermind crash report',
    '',
    '## Error',
    `- **time**: ${at.toISOString()}`,
    `- **skill**: ${ctx.skill ?? 'unknown'}`,
    formatErrorChain(ctx.error),
    '',
    '## Context',
    `- **caller**: ${ctx.caller ?? 'unknown'}`,
    ctx.sessionId ? `- **sessionId**: ${ctx.sessionId}` : '',
    ctx.mode ? `- **mode**: ${ctx.mode}` : '',
    ctx.args ? `- **args**: \`${JSON.stringify(ctx.args)}\`` : '',
    `- **prompt** (first ${PROMPT_PREVIEW_LIMIT} chars):`,
    '```',
    promptPreview,
    '```',
    '',
  ].filter(Boolean).join('\n');
};

export const writeCrashReport = async (ctx: TCrashContext): Promise<string> => {
  await fs.mkdir(paths.crashReports, { recursive: true });

  const at = new Date();
  const absolute = path.join(paths.crashReports, crashReportFilename(at));
  const body = buildCrashReportBody(ctx, at);

  await fs.writeFile(absolute, body, 'utf8');

  return absolute;
};

const appendAnalysisSection = async (reportPath: string, content: string) => {
  const section = [
    '## Analysis',
    '(auto-generated by crash analyst agent)',
    '',
    content.trim(),
    '',
  ].join('\n');

  await fs.appendFile(reportPath, section, 'utf8');
};

const appendAnalysisFailure = async (reportPath: string, error: unknown) => {
  const message = formatShortError(error);

  await appendAnalysisSection(
    reportPath,
    `(analysis failed: ${message})`,
  );
};

const runCrashAnalysis = async (reportPath: string, ctx: TCrashContext) => {
  if (!config.apiKey) {
    await appendAnalysisFailure(reportPath, new Error('CURSOR_API_KEY missing'));

    return;
  }

  const { Agent } = await import('@cursor/sdk');

  const diagnosticPrompt = [
    'You are the YAHL mastermind crash analyst.',
    'Given the error and context below, list likely causes and suggested operator actions.',
    'Do not propose or make code changes. Output markdown only.',
    '',
    buildCrashReportBody(ctx, new Date()),
  ].join('\n');

  try {
    const result = await Agent.prompt(diagnosticPrompt, {
      apiKey: config.apiKey,
      local: { cwd: config.workspaceRoot },
      model: { id: 'auto' },
    });

    await appendAnalysisSection(reportPath, result.result ?? '(empty analysis)');
  } catch (error) {
    await appendAnalysisFailure(reportPath, error);
  }
};

export const writeAndAnalyzeCrash = async (ctx: TCrashContext): Promise<string> => {
  const reportPath = await writeCrashReport(ctx);

  void runCrashAnalysis(reportPath, ctx).catch((error) => {
    console.error('[mastermind] crash analysis failed', error);
  });

  return reportPath;
};

const DEDUP_WINDOW_MS = 30_000;

let lastReportedMessage = '';
let lastReportedAt = 0;
let reportingProcessCrash = false;

export const reportProcessLevelCrash = async (
  error: unknown,
  skill: 'process' | 'startup',
): Promise<void> => {
  console.error(`[mastermind] ${skill} crash`, error);

  if (reportingProcessCrash) {
    return;
  }

  const message = formatShortError(error);
  const now = Date.now();

  if (message === lastReportedMessage && now - lastReportedAt < DEDUP_WINDOW_MS) {
    return;
  }

  reportingProcessCrash = true;
  lastReportedMessage = message;
  lastReportedAt = now;

  try {
    await writeAndAnalyzeCrash({
      caller: 'mastermind',
      error,
      skill,
    });
  } catch (reportError) {
    console.error('[mastermind] crash report failed', reportError);
  } finally {
    reportingProcessCrash = false;
  }
};
