export {
  buildWikiAncestorPaths,
  corpusConfigured,
  createWikiPage,
  deleteWikiPage,
  ensureWikiPageAncestors,
  getWikiPageByPath,
  listWikiPagesUnderPrefix,
  searchWikiPages,
  updateWikiPage,
  upsertWikiPage,
  wikiConfigured,
  type TPageRecord,
  type TUpsertWikiMode,
} from './corpus-client.js';
